//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.Relatorica.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avance
    {
        public int AvanceId { get; set; }
        public Nullable<int> HijoId { get; set; }
        public Nullable<decimal> PorcentajeAvance { get; set; }
        public Nullable<int> ParrafoId { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Hijo Hijo { get; set; }
        public virtual Parrafo Parrafo { get; set; }
    }
}
