//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.Relatorica.Service.MakeSolution.Relatorica.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int CompraId { get; set; }
        public Nullable<int> PadreId { get; set; }
        public Nullable<int> HistoriaId { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Costo { get; set; }
    
        public virtual Historia Historia { get; set; }
        public virtual Padre Padre { get; set; }
    }
}
