//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.Relatorica.Service.MakeSolution.Relatorica.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Padre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Padre()
        {
            this.Compra = new HashSet<Compra>();
            this.Hijo = new HashSet<Hijo>();
        }
    
        public int PadreId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Credenciales { get; set; }
        public string Contrasenia { get; set; }
        public string Correo { get; set; }
        public string Celular { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> DistritoId { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        public virtual Distrito Distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hijo> Hijo { get; set; }
    }
}
