//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.Relatorica.Service.MakeSolution.Relatorica.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RelatoricaEntities : DbContext
    {
        public RelatoricaEntities()
            : base("name=RelatoricaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avance> Avance { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Hijo> Hijo { get; set; }
        public virtual DbSet<Historia> Historia { get; set; }
        public virtual DbSet<Padre> Padre { get; set; }
        public virtual DbSet<Parrafo> Parrafo { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Sonido> Sonido { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
