//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.Relatorica.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sonido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sonido()
        {
            this.Parrafo = new HashSet<Parrafo>();
        }
    
        public int SonidoId { get; set; }
        public string Nombre { get; set; }
        public string Url { get; set; }
        public Nullable<int> GeneroId { get; set; }
        public string Estado { get; set; }
        public string FechaRegistro { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parrafo> Parrafo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
