//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.Relatorica.Service.MakeSolution.Relatorica.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sonido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sonido()
        {
            this.Parrafo = new HashSet<Parrafo>();
        }
    
        public int SonidoId { get; set; }
        public string Nombre { get; set; }
        public string Url { get; set; }
        public Nullable<int> GeneroId { get; set; }
        public string Estado { get; set; }
        public string FechaRegistro { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parrafo> Parrafo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
