//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSolution.Relatorica.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int CompraId { get; set; }
        public Nullable<int> PadreId { get; set; }
        public Nullable<int> HistoriaId { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Costo { get; set; }
    
        public virtual Historia Historia { get; set; }
        public virtual Padre Padre { get; set; }
    }
}
